#!/usr/bin/env sh

spacebar -m config position            top
spacebar -m config icon_font "FiraCode Nerd Font:Light:11.0"
spacebar -m config clock_format         "%R"
spacebar -m config space_icon_strip 1 2 3 4
spacebar -m config power_icon_strip   
spacebar -m config background_color     0xff000000
spacebar -m config battery_icon_color 0xffFFE45E
spacebar -m config space_icon_color 0xff7FC8F8
spacebar -m config clock_icon_color 0xff7FC8F8
spacebar -m config foreground_color     0x8fffffff
spacebar -m config height 20
spacebar -m config padding_left        10
spacebar -m config title                       off
spacebar -m config clock_icon          
