#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         0
bspc config window_gap           2 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xgamma -gamma 1.5 &
xset r rate 300 50 
bash /home/spheal/.config/bspwm/bspwm_colors.sh &
/home/spheal/.config/polybar/launch.sh &
feh --bg-fill /home/spheal/pic/wall/redsun.png &
picom --config ~/.config/picom/picom.conf &

