#! /bin/sh
bspc rule -r "*"
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         0
bspc config window_gap           2 
bspc config top_padding          30
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

xgamma -gamma 1.5 &
xset r rate 300 50 
bash /home/spheal/.config/bspwm/bspwm_colors.sh &
/home/spheal/.config/polybar/launch.sh &
feh --bg-fill /home/spheal/pic/wall/cur &
picom --config ~/.config/picom/picom.conf &
xinput --set-prop "Logitech Gaming Mouse G502" "libinput Accel Speed" 0.8
bspswallow &

bspc rule -a Emacs state=tiled manage=on layer=normal sticky=off follow=off

bspc rule -a Zathura state=tiled manage=on layer=normal sticky=off follow=off
emacs --daemon
