#! /bin/sh
bspc rule -r "*"
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  ﮊ  懲 

bspc config border_width         0
bspc config window_gap           6 
bspc config top_padding          0
bspc config bottom_padding       0
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

tint2 &
xgamma -gamma 1.3 &
xset r rate 300 50 
feh --bg-fill /home/spheal/pic/wall/cur &
picom --config ~/.config/picom/picom.conf &
xinput --set-prop "Logitech Gaming Mouse G502" "libinput Accel Speed" 0.8
bspc rule -a Emacs manage=on state=tiled
bspc rule -a Thunar state=floating
xinput set-prop 11 156 3.4 0 0 0 3.4 0 0 0 1
redshift -r -l 33.02:-96.7
(ps x | grep swallow | grep -v grep) || $HOME/bin/swallow &

