let mapleader=" "
set relativenumber
set nu
set hidden
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set undofile
set wildmenu
set wildmode=list:longest
set scrolloff=3
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set nohlsearch
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set wildmenu
set wildmode=list:longest,list:full
